version: "3"

services:

  app:
    build:
      context: .
      dockerfile: app.Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://localhost:3306/javacode
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root

  db:
    build:
      context: .
      dockerfile: postgreSQL.Dockerfile
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: javacode
      TZ: Europe/Moscow
      command: --init-file db/initDB.sql
    ports:
      - "3306:3306"

