version: "3"

services:

  app:
    build:
      context: .
      dockerfile: app.Dockerfile
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/javacode
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
    ports:
      - "8080:8080"
    command: ["./wait-for-it.sh", "db:5432", "java", "-jar", "/app/app.war"]
    networks:
      app:

  psql:
    build:
      context: .
      dockerfile: postgreSQL.Dockerfile
    container_name: db
    environment:
      POSTGRES_DB: javacode
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./db/initDB.sql:/docker-entrypoint-initdb.d/initDB.sql
    networks:
      app:

networks:
  app:
    driver: bridge
