version: "3"

services:

  app:
    build:
      context: .
      dockerfile: app.Dockerfile
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/javacode
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
    ports:
      - "8080:8080"
    command: ["./wait-for-it.sh", "db:5432", "java", "-jar", "/app/app.war"]

  db:
    build:
      context: .
      dockerfile: postgreSQL.Dockerfile
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: javacode
    ports:
      - "5432:5432"

